"""update models

Revision ID: 32091dc7a67f
Revises: f8b8118d9bd4
Create Date: 2025-08-15 17:49:25.511301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32091dc7a67f'
down_revision: Union[str, Sequence[str], None] = 'f8b8118d9bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_company_links_id'), 'company_links', ['id'], unique=False)
    op.drop_index(op.f('ix_social_links_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_column('companies', 'url_site')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('url_site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('social_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discovered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('social_links_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_links_pkey')),
    sa.UniqueConstraint('url', name=op.f('social_links_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_social_links_id'), 'social_links', ['id'], unique=False)
    op.drop_index(op.f('ix_company_links_id'), table_name='company_links')
    op.drop_table('company_links')
    # ### end Alembic commands ###
