"""change constrains for AUMSnapshot

Revision ID: f8b8118d9bd4
Revises: 761afc8bef59
Create Date: 2025-08-15 11:57:45.523025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b8118d9bd4'
down_revision: Union[str, Sequence[str], None] = '761afc8bef59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aum_snapshots', 'aum_unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('aum_snapshots', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('aum_snapshots', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aum_snapshots', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('aum_snapshots', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('aum_snapshots', 'aum_unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
